receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  gelf:
    listen_address: "0.0.0.0:12201"
    protocol: "both" # Support both TCP and UDP
    use_compression: true
    max_message_size: 8192
    read_timeout: "30s"
    write_timeout: "30s"
    chunk_timeout: "5s"

processors:
  batch:


exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]
    logs:
      receivers: [ gelf, otlp ]
      processors: [ batch ]
      exporters: [ debug ]

  telemetry:
    logs:
      level: debug
